function VM112(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18) {
 var v0,v1,v2; // BYTECODE_POS: GENERATED
 var executionStack = [];          //BYTECODE_POS: GENEREATED 
 v0 = Uint8Array                   //BYTECODE_POS: 1 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v1 = 19;                          //BYTECODE_POS: 3 
 v0 = new v0()                     //BYTECODE_POS: 5 
 executionStack[21] = v0;          //BYTECODE_POS: 7 // depth = 0
 v0 = executionStack[21];          //BYTECODE_POS: 10 depth
 v1 = executionStack[2];           //BYTECODE_POS: 13 depth
 v0.0 = v0;                        //BYTECODE_POS: 16 
 v0 = executionStack[21];          //BYTECODE_POS: 18 depth
 v1 = executionStack[12];          //BYTECODE_POS: 21 depth
 v0.1 = v0;                        //BYTECODE_POS: 24 
 v0 = executionStack[21];          //BYTECODE_POS: 26 depth
 v1 = executionStack[3];           //BYTECODE_POS: 29 depth
 v0.2 = v0;                        //BYTECODE_POS: 32 
 v0 = executionStack[21];          //BYTECODE_POS: 34 depth
 v1 = executionStack[13];          //BYTECODE_POS: 37 depth
 v0.3 = v0;                        //BYTECODE_POS: 40 
 v0 = executionStack[21];          //BYTECODE_POS: 42 depth
 v1 = executionStack[4];           //BYTECODE_POS: 45 depth
 v0.4 = v0;                        //BYTECODE_POS: 48 
 v0 = executionStack[21];          //BYTECODE_POS: 50 depth
 v1 = executionStack[14];          //BYTECODE_POS: 53 depth
 v0.5 = v0;                        //BYTECODE_POS: 56 
 v0 = executionStack[21];          //BYTECODE_POS: 58 depth
 v1 = executionStack[5];           //BYTECODE_POS: 61 depth
 v0.6 = v0;                        //BYTECODE_POS: 64 
 v0 = executionStack[21];          //BYTECODE_POS: 66 depth
 v1 = executionStack[15];          //BYTECODE_POS: 69 depth
 v0.7 = v0;                        //BYTECODE_POS: 72 
 v0 = executionStack[21];          //BYTECODE_POS: 74 depth
 v1 = executionStack[6];           //BYTECODE_POS: 77 depth
 v0.8 = v0;                        //BYTECODE_POS: 80 
 v0 = executionStack[21];          //BYTECODE_POS: 82 depth
 v1 = executionStack[16];          //BYTECODE_POS: 85 depth
 v0.9 = v0;                        //BYTECODE_POS: 88 
 v0 = executionStack[21];          //BYTECODE_POS: 90 depth
 v1 = executionStack[7];           //BYTECODE_POS: 93 depth
 v0.10 = v0;                       //BYTECODE_POS: 96 
 v0 = executionStack[21];          //BYTECODE_POS: 98 depth
 v1 = executionStack[17];          //BYTECODE_POS: 101 depth
 v0.11 = v0;                       //BYTECODE_POS: 104 
 v0 = executionStack[21];          //BYTECODE_POS: 106 depth
 v1 = executionStack[8];           //BYTECODE_POS: 109 depth
 v0.12 = v0;                       //BYTECODE_POS: 112 
 v0 = executionStack[21];          //BYTECODE_POS: 114 depth
 v1 = executionStack[18];          //BYTECODE_POS: 117 depth
 v0.13 = v0;                       //BYTECODE_POS: 120 
 v0 = executionStack[21];          //BYTECODE_POS: 122 depth
 v1 = executionStack[9];           //BYTECODE_POS: 125 depth
 v0.14 = v0;                       //BYTECODE_POS: 128 
 v0 = executionStack[21];          //BYTECODE_POS: 130 depth
 v1 = executionStack[19];          //BYTECODE_POS: 133 depth
 v0.15 = v0;                       //BYTECODE_POS: 136 
 v0 = executionStack[21];          //BYTECODE_POS: 138 depth
 v1 = executionStack[10];          //BYTECODE_POS: 141 depth
 v0.16 = v0;                       //BYTECODE_POS: 144 
 v0 = executionStack[21];          //BYTECODE_POS: 146 depth
 v1 = executionStack[20];          //BYTECODE_POS: 149 depth
 v0.17 = v0;                       //BYTECODE_POS: 152 
 v0 = executionStack[21];          //BYTECODE_POS: 154 depth
 v1 = executionStack[11];          //BYTECODE_POS: 157 depth
 v0.18 = v0;                       //BYTECODE_POS: 160 
 v0 = String                       //BYTECODE_POS: 162 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v0.fromCharCode;             //BYTECODE_POS: 164 
 v1 = v0                           //BYTECODE_POS: 166 
 v1 = v1.apply;                    //BYTECODE_POS: 167 
 v2 = null                         //BYTECODE_POS: 169 
 v3 = executionStack[21];          //BYTECODE_POS: 170 depth
 v0 = v1(v2,v3);                   //BYTECODE_POS: 173 // context 0 could be custom vm or native func
 //return v0;                      //BYTECODE_POS: 175 
}