function VM138() {
 var v0,v1,v2,v3; // BYTECODE_POS: GENERATED
 var executionStack = [];          //BYTECODE_POS: GENEREATED 
 v0 = document                     //BYTECODE_POS: 1 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v1 = v0                           //BYTECODE_POS: 3 
 v1 = v1.createElement;            //BYTECODE_POS: 4 
 v2 = "canvas"                     //BYTECODE_POS: 6 
 v0 = v1(v2);                      //BYTECODE_POS: 8 // context 0 could be custom vm or native func
 executionStack[2] = v0;           //BYTECODE_POS: 10 // depth = 0
 v0 = HTMLCanvasElement            //BYTECODE_POS: 13 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v0.prototype;                //BYTECODE_POS: 15 
 executionStack[3] = v0;           //BYTECODE_POS: 17 // depth = 0
 v0 = CanvasRenderingContext2D     //BYTECODE_POS: 20 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v0.prototype;                //BYTECODE_POS: 22 
 executionStack[4] = v0;           //BYTECODE_POS: 24 // depth = 0
 v0 = executionStack[2];           //BYTECODE_POS: 27 depth
 v1 = v0                           //BYTECODE_POS: 30 
 v1 = v1.getContext;               //BYTECODE_POS: 31 
 v2 = "2d"                         //BYTECODE_POS: 33 
 v0 = v1(v2);                      //BYTECODE_POS: 35 // context 0 could be custom vm or native func
 executionStack[5] = v0;           //BYTECODE_POS: 37 // depth = 0
 v0 = {};                          //BYTECODE_POS: 40 
 v1 = ""                           //BYTECODE_POS: 41 
 v2 = undefined                    //BYTECODE_POS: 43 
 v3 = executionStack[4];           //BYTECODE_POS: 44 depth
 v4 = Function                     //BYTECODE_POS: 47 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.prototype;                //BYTECODE_POS: 49 
 v2 = v3(v4);                      //BYTECODE_POS: 51 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 53 
 v2 = undefined                    //BYTECODE_POS: 54 
 v3 = executionStack[4];           //BYTECODE_POS: 55 depth
 v4 = Function                     //BYTECODE_POS: 58 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.prototype;                //BYTECODE_POS: 60 
 v4 = v4.toString;                 //BYTECODE_POS: 62 
 v2 = v3(v4);                      //BYTECODE_POS: 64 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 66 
 v2 = undefined                    //BYTECODE_POS: 67 
 v3 = executionStack[4];           //BYTECODE_POS: 68 depth
 v4 = Navigator                    //BYTECODE_POS: 71 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.prototype;                //BYTECODE_POS: 73 
 v4 = v4.toString;                 //BYTECODE_POS: 75 
 v2 = v3(v4);                      //BYTECODE_POS: 77 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 79 
 v2 = undefined                    //BYTECODE_POS: 80 
 v3 = executionStack[4];           //BYTECODE_POS: 81 depth
 v4 = Object                       //BYTECODE_POS: 84 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.prototype;                //BYTECODE_POS: 86 
 v4 = v4.toString;                 //BYTECODE_POS: 88 
 v2 = v3(v4);                      //BYTECODE_POS: 90 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 92 
 v2 = undefined                    //BYTECODE_POS: 93 
 v3 = executionStack[4];           //BYTECODE_POS: 94 depth
 v4 = JSON                         //BYTECODE_POS: 97 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.stringify;                //BYTECODE_POS: 99 
 v2 = v3(v4);                      //BYTECODE_POS: 101 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 103 
 v2 = undefined                    //BYTECODE_POS: 104 
 v3 = executionStack[4];           //BYTECODE_POS: 105 depth
 v4 = executionStack[3];           //BYTECODE_POS: 108 depth
 v2 = v3(v4);                      //BYTECODE_POS: 111 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 113 
 v2 = undefined                    //BYTECODE_POS: 114 
 v3 = executionStack[4];           //BYTECODE_POS: 115 depth
 v4 = executionStack[3];           //BYTECODE_POS: 118 depth
 v4 = v4.getContext;               //BYTECODE_POS: 121 
 v2 = v3(v4);                      //BYTECODE_POS: 123 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 125 
 v2 = undefined                    //BYTECODE_POS: 126 
 v3 = executionStack[4];           //BYTECODE_POS: 127 depth
 v4 = executionStack[4];           //BYTECODE_POS: 130 depth
 v2 = v3(v4);                      //BYTECODE_POS: 133 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 135 
 v2 = undefined                    //BYTECODE_POS: 136 
 v3 = executionStack[4];           //BYTECODE_POS: 137 depth
 v4 = executionStack[4];           //BYTECODE_POS: 140 depth
 v4 = v4.getContext;               //BYTECODE_POS: 143 
 v2 = v3(v4);                      //BYTECODE_POS: 145 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 147 
 v2 = undefined                    //BYTECODE_POS: 148 
 v3 = executionStack[4];           //BYTECODE_POS: 149 depth
 v4 = executionStack[5];           //BYTECODE_POS: 152 depth
 v4 = v4.getImageData;             //BYTECODE_POS: 155 
 v2 = v3(v4);                      //BYTECODE_POS: 157 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 159 
 v2 = undefined                    //BYTECODE_POS: 160 
 v3 = executionStack[4];           //BYTECODE_POS: 161 depth
 v4 = executionStack[4];           //BYTECODE_POS: 164 depth
 v4 = v4.getImageData;             //BYTECODE_POS: 167 
 v2 = v3(v4);                      //BYTECODE_POS: 169 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 171 
 v2 = undefined                    //BYTECODE_POS: 172 
 v3 = executionStack[4];           //BYTECODE_POS: 173 depth
 v4 = window                       //BYTECODE_POS: 176 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.setInterval;              //BYTECODE_POS: 178 
 v2 = v3(v4);                      //BYTECODE_POS: 180 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 182 
 v2 = undefined                    //BYTECODE_POS: 183 
 v3 = executionStack[4];           //BYTECODE_POS: 184 depth
 v4 = window                       //BYTECODE_POS: 187 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.setTimeout;               //BYTECODE_POS: 189 
 v2 = v3(v4);                      //BYTECODE_POS: 191 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 193 
 v2 = undefined                    //BYTECODE_POS: 194 
 v3 = executionStack[4];           //BYTECODE_POS: 195 depth
 v4 = window                       //BYTECODE_POS: 198 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.localStorage;             //BYTECODE_POS: 200 
 v4 = v4.getItem;                  //BYTECODE_POS: 202 
 v2 = v3(v4);                      //BYTECODE_POS: 204 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 206 
 v2 = undefined                    //BYTECODE_POS: 207 
 v3 = executionStack[4];           //BYTECODE_POS: 208 depth
 v4 = window                       //BYTECODE_POS: 211 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.localStorage;             //BYTECODE_POS: 213 
 v4 = v4.setItem;                  //BYTECODE_POS: 215 
 v2 = v3(v4);                      //BYTECODE_POS: 217 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 219 
 v2 = undefined                    //BYTECODE_POS: 220 
 v3 = executionStack[4];           //BYTECODE_POS: 221 depth
 v4 = window                       //BYTECODE_POS: 224 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.sessionStorage;           //BYTECODE_POS: 226 
 v4 = v4.getItem;                  //BYTECODE_POS: 228 
 v2 = v3(v4);                      //BYTECODE_POS: 230 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 232 
 v2 = undefined                    //BYTECODE_POS: 233 
 v3 = executionStack[4];           //BYTECODE_POS: 234 depth
 v4 = window                       //BYTECODE_POS: 237 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.sessionStorage;           //BYTECODE_POS: 239 
 v4 = v4.setItem;                  //BYTECODE_POS: 241 
 v2 = v3(v4);                      //BYTECODE_POS: 243 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 245 
 v0.data = v1;                     //BYTECODE_POS: 246 
 //return v0;                      //BYTECODE_POS: 248 
}