function VM14() {
 var v0,v1,v2,v3,v4,v5; // BYTECODE_POS: GENERATED
 var executionStack = [];          //BYTECODE_POS: GENEREATED 
 v0 = executionStack[2];           //BYTECODE_POS: 1 depth
 v0 = v0.navigator;                //BYTECODE_POS: 4 
 v1 = ""                           //BYTECODE_POS: 6 
 v2 = navigator                    //BYTECODE_POS: 8 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.appCodeName;              //BYTECODE_POS: 10 
 v1 += v2                          //BYTECODE_POS: 12 
 v0.appCodeName = v0;              //BYTECODE_POS: 13 
 v0 = executionStack[2];           //BYTECODE_POS: 15 depth
 v0 = v0.navigator;                //BYTECODE_POS: 18 
 v1 = ""                           //BYTECODE_POS: 20 
 v2 = navigator                    //BYTECODE_POS: 22 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.appMinorVersion;          //BYTECODE_POS: 24 
 v1 += v2                          //BYTECODE_POS: 26 
 v0.appMinorVersion = v0;          //BYTECODE_POS: 27 
 v0 = executionStack[2];           //BYTECODE_POS: 29 depth
 v0 = v0.navigator;                //BYTECODE_POS: 32 
 v1 = ""                           //BYTECODE_POS: 34 
 v2 = navigator                    //BYTECODE_POS: 36 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.appName;                  //BYTECODE_POS: 38 
 v1 += v2                          //BYTECODE_POS: 40 
 v0.appName = v0;                  //BYTECODE_POS: 41 
 v0 = executionStack[2];           //BYTECODE_POS: 43 depth
 v0 = v0.navigator;                //BYTECODE_POS: 46 
 v1 = ""                           //BYTECODE_POS: 48 
 v2 = navigator                    //BYTECODE_POS: 50 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.appVersion;               //BYTECODE_POS: 52 
 v1 += v2                          //BYTECODE_POS: 54 
 v0.appVersion = v0;               //BYTECODE_POS: 55 
 v0 = executionStack[2];           //BYTECODE_POS: 57 depth
 v0 = v0.navigator;                //BYTECODE_POS: 60 
 v1 = ""                           //BYTECODE_POS: 62 
 v2 = navigator                    //BYTECODE_POS: 64 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.buildID;                  //BYTECODE_POS: 66 
 v1 += v2                          //BYTECODE_POS: 68 
 v0.buildID = v0;                  //BYTECODE_POS: 69 
 v0 = executionStack[2];           //BYTECODE_POS: 71 depth
 v0 = v0.navigator;                //BYTECODE_POS: 74 
 v1 = ""                           //BYTECODE_POS: 76 
 v2 = navigator                    //BYTECODE_POS: 78 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.doNotTrack;               //BYTECODE_POS: 80 
 v1 += v2                          //BYTECODE_POS: 82 
 v0.doNotTrack = v0;               //BYTECODE_POS: 83 
 v0 = executionStack[2];           //BYTECODE_POS: 85 depth
 v0 = v0.navigator;                //BYTECODE_POS: 88 
 v1 = ""                           //BYTECODE_POS: 90 
 v2 = navigator                    //BYTECODE_POS: 92 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.msDoNotTrack;             //BYTECODE_POS: 94 
 v1 += v2                          //BYTECODE_POS: 96 
 v0.msDoNotTrack = v0;             //BYTECODE_POS: 97 
 v0 = executionStack[2];           //BYTECODE_POS: 99 depth
 v0 = v0.navigator;                //BYTECODE_POS: 102 
 v1 = ""                           //BYTECODE_POS: 104 
 v2 = navigator                    //BYTECODE_POS: 106 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.oscpu;                    //BYTECODE_POS: 108 
 v1 += v2                          //BYTECODE_POS: 110 
 v0.oscpu = v0;                    //BYTECODE_POS: 111 
 v0 = executionStack[2];           //BYTECODE_POS: 113 depth
 v0 = v0.navigator;                //BYTECODE_POS: 116 
 v1 = ""                           //BYTECODE_POS: 118 
 v2 = navigator                    //BYTECODE_POS: 120 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.platform;                 //BYTECODE_POS: 122 
 v1 += v2                          //BYTECODE_POS: 124 
 v0.platform = v0;                 //BYTECODE_POS: 125 
 v0 = executionStack[2];           //BYTECODE_POS: 127 depth
 v0 = v0.navigator;                //BYTECODE_POS: 130 
 v1 = ""                           //BYTECODE_POS: 132 
 v2 = navigator                    //BYTECODE_POS: 134 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.product;                  //BYTECODE_POS: 136 
 v1 += v2                          //BYTECODE_POS: 138 
 v0.product = v0;                  //BYTECODE_POS: 139 
 v0 = executionStack[2];           //BYTECODE_POS: 141 depth
 v0 = v0.navigator;                //BYTECODE_POS: 144 
 v1 = ""                           //BYTECODE_POS: 146 
 v2 = navigator                    //BYTECODE_POS: 148 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.productSub;               //BYTECODE_POS: 150 
 v1 += v2                          //BYTECODE_POS: 152 
 v0.productSub = v0;               //BYTECODE_POS: 153 
 v0 = executionStack[2];           //BYTECODE_POS: 155 depth
 v0 = v0.navigator;                //BYTECODE_POS: 158 
 v1 = ""                           //BYTECODE_POS: 160 
 v2 = navigator                    //BYTECODE_POS: 162 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.cpuClass;                 //BYTECODE_POS: 164 
 v1 += v2                          //BYTECODE_POS: 166 
 v0.cpuClass = v0;                 //BYTECODE_POS: 167 
 v0 = executionStack[2];           //BYTECODE_POS: 169 depth
 v0 = v0.navigator;                //BYTECODE_POS: 172 
 v1 = ""                           //BYTECODE_POS: 174 
 v2 = navigator                    //BYTECODE_POS: 176 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.vendor;                   //BYTECODE_POS: 178 
 v1 += v2                          //BYTECODE_POS: 180 
 v0.vendor = v0;                   //BYTECODE_POS: 181 
 v0 = executionStack[2];           //BYTECODE_POS: 183 depth
 v0 = v0.navigator;                //BYTECODE_POS: 186 
 v1 = ""                           //BYTECODE_POS: 188 
 v2 = navigator                    //BYTECODE_POS: 190 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.vendorSub;                //BYTECODE_POS: 192 
 v1 += v2                          //BYTECODE_POS: 194 
 v0.vendorSub = v0;                //BYTECODE_POS: 195 
 v0 = executionStack[2];           //BYTECODE_POS: 197 depth
 v0 = v0.navigator;                //BYTECODE_POS: 200 
 v1 = ""                           //BYTECODE_POS: 202 
 v2 = navigator                    //BYTECODE_POS: 204 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.deviceMemory;             //BYTECODE_POS: 206 
 v1 += v2                          //BYTECODE_POS: 208 
 v0.deviceMemory = v0;             //BYTECODE_POS: 209 
 v0 = executionStack[2];           //BYTECODE_POS: 211 depth
 v0 = v0.navigator;                //BYTECODE_POS: 214 
 v1 = ""                           //BYTECODE_POS: 216 
 v2 = navigator                    //BYTECODE_POS: 218 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.language;                 //BYTECODE_POS: 220 
 v1 += v2                          //BYTECODE_POS: 222 
 v0.language = v0;                 //BYTECODE_POS: 223 
 v0 = executionStack[2];           //BYTECODE_POS: 225 depth
 v0 = v0.navigator;                //BYTECODE_POS: 228 
 v1 = ""                           //BYTECODE_POS: 230 
 v2 = navigator                    //BYTECODE_POS: 232 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.systemLanguage;           //BYTECODE_POS: 234 
 v1 += v2                          //BYTECODE_POS: 236 
 v0.systemLanguage = v0;           //BYTECODE_POS: 237 
 v0 = executionStack[2];           //BYTECODE_POS: 239 depth
 v0 = v0.navigator;                //BYTECODE_POS: 242 
 v1 = ""                           //BYTECODE_POS: 244 
 v2 = navigator                    //BYTECODE_POS: 246 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.userLanguage;             //BYTECODE_POS: 248 
 v1 += v2                          //BYTECODE_POS: 250 
 v0.userLanguage = v0;             //BYTECODE_POS: 251 
 v0 = executionStack[2];           //BYTECODE_POS: 253 depth
 v0 = v0.navigator;                //BYTECODE_POS: 256 
 v1 = ""                           //BYTECODE_POS: 258 
 v2 = navigator                    //BYTECODE_POS: 260 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.webdriver;                //BYTECODE_POS: 262 
 v1 += v2                          //BYTECODE_POS: 264 
 v0.webdriver = v0;                //BYTECODE_POS: 265 
 v0 = executionStack[2];           //BYTECODE_POS: 267 depth
 v0 = v0.navigator;                //BYTECODE_POS: 270 
 v1 = navigator                    //BYTECODE_POS: 272 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v1 = v1.hardwareConcurrency;      //BYTECODE_POS: 274 
 v1 = typeof v1;                   //BYTECODE_POS: 276 
 v2 = "number"                     //BYTECODE_POS: 277 
 v1 = v1 === v2                    //BYTECODE_POS: 279 
 // if (!v1) skip to 294           //BYTECODE_POS: 280 
 v1 = Math                         //BYTECODE_POS: 282 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v1                           //BYTECODE_POS: 284 
 v2 = v2.floor;                    //BYTECODE_POS: 285 
 v3 = navigator                    //BYTECODE_POS: 287 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.hardwareConcurrency;      //BYTECODE_POS: 289 
 v1 = v2(v3);                      //BYTECODE_POS: 291 // context 1 could be custom vm or native func
 // go foward to 297               //BYTECODE_POS: 293 
 v2 = 1;                           //BYTECODE_POS: 295 
 v2 = -v2                          //BYTECODE_POS: 297 
 v1.hardwareConcurrency = v1;      //BYTECODE_POS: 298 
 v1 = executionStack[2];           //BYTECODE_POS: 300 depth
 v1 = v1.navigator;                //BYTECODE_POS: 303 
 v2 = navigator                    //BYTECODE_POS: 305 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.maxTouchPoints;           //BYTECODE_POS: 307 
 v2 = typeof v2;                   //BYTECODE_POS: 309 
 v3 = "number"                     //BYTECODE_POS: 310 
 v2 = v2 === v3                    //BYTECODE_POS: 312 
 // if (!v2) skip to 327           //BYTECODE_POS: 313 
 v2 = Math                         //BYTECODE_POS: 315 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v2                           //BYTECODE_POS: 317 
 v3 = v3.floor;                    //BYTECODE_POS: 318 
 v4 = navigator                    //BYTECODE_POS: 320 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.maxTouchPoints;           //BYTECODE_POS: 322 
 v2 = v3(v4);                      //BYTECODE_POS: 324 // context 2 could be custom vm or native func
 // go foward to 330               //BYTECODE_POS: 326 
 v3 = 1;                           //BYTECODE_POS: 328 
 v3 = -v3                          //BYTECODE_POS: 330 
 v2.maxTouchPoints = v2;           //BYTECODE_POS: 331 
 v2 = executionStack[2];           //BYTECODE_POS: 333 depth
 v2 = v2.navigator;                //BYTECODE_POS: 336 
 v3 = undefined                    //BYTECODE_POS: 338 
 v4 = executionStack[14];          //BYTECODE_POS: 339 depth
 v5 = navigator                    //BYTECODE_POS: 342 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v5 = v5.cookieEnabled;            //BYTECODE_POS: 344 
 v3 = v4(v5);                      //BYTECODE_POS: 346 // context 3 could be custom vm or native func
 v2.cookieEnabled = v2;            //BYTECODE_POS: 348 
 v2 = executionStack[2];           //BYTECODE_POS: 350 depth
 v2 = v2.navigator;                //BYTECODE_POS: 353 
 v3 = undefined                    //BYTECODE_POS: 355 
 v4 = executionStack[14];          //BYTECODE_POS: 356 depth
 v5 = navigator                    //BYTECODE_POS: 359 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v5 = v5.vibrate;                  //BYTECODE_POS: 361 
 v3 = v4(v5);                      //BYTECODE_POS: 363 // context 3 could be custom vm or native func
 v2.vibrate = v2;                  //BYTECODE_POS: 365 
 v2 = executionStack[2];           //BYTECODE_POS: 367 depth
 v2 = v2.navigator;                //BYTECODE_POS: 370 
 v3 = undefined                    //BYTECODE_POS: 372 
 v4 = executionStack[14];          //BYTECODE_POS: 373 depth
 v5 = navigator                    //BYTECODE_POS: 376 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v5 = v5.credentials;              //BYTECODE_POS: 378 
 v3 = v4(v5);                      //BYTECODE_POS: 380 // context 3 could be custom vm or native func
 v2.credentials = v2;              //BYTECODE_POS: 382 
 v2 = executionStack[2];           //BYTECODE_POS: 384 depth
 v2 = v2.navigator;                //BYTECODE_POS: 387 
 v3 = undefined                    //BYTECODE_POS: 389 
 v4 = executionStack[14];          //BYTECODE_POS: 390 depth
 v5 = navigator                    //BYTECODE_POS: 393 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v5 = v5.storage;                  //BYTECODE_POS: 395 
 v3 = v4(v5);                      //BYTECODE_POS: 397 // context 3 could be custom vm or native func
 v2.storage = v2;                  //BYTECODE_POS: 399 
 v2 = executionStack[2];           //BYTECODE_POS: 401 depth
 v2 = v2.navigator;                //BYTECODE_POS: 404 
 v3 = undefined                    //BYTECODE_POS: 406 
 v4 = executionStack[14];          //BYTECODE_POS: 407 depth
 v5 = navigator                    //BYTECODE_POS: 410 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v5 = v5.requestMediaKeySystemAccess;//BYTECODE_POS: 412 
 v3 = v4(v5);                      //BYTECODE_POS: 414 // context 3 could be custom vm or native func
 v2.requestMediaKeySystemAccess = v2;//BYTECODE_POS: 416 
 v2 = executionStack[2];           //BYTECODE_POS: 418 depth
 v2 = v2.navigator;                //BYTECODE_POS: 421 
 v3 = undefined                    //BYTECODE_POS: 423 
 v4 = executionStack[14];          //BYTECODE_POS: 424 depth
 v5 = navigator                    //BYTECODE_POS: 427 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v5 = v5.bluetooth;                //BYTECODE_POS: 429 
 v3 = v4(v5);                      //BYTECODE_POS: 431 // context 3 could be custom vm or native func
 v2.bluetooth = v2;                //BYTECODE_POS: 433 
 v2 = executionStack[2];           //BYTECODE_POS: 435 depth
 v2 = v2.navigator;                //BYTECODE_POS: 438 
 v3 = undefined                    //BYTECODE_POS: 440 
 v4 = executionStack[0];           //BYTECODE_POS: 441 depth
 v5 = navigator                    //BYTECODE_POS: 444 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v5 = v5.languages;                //BYTECODE_POS: 446 
 v3 = v4(v5);                      //BYTECODE_POS: 448 // context 3 could be custom vm or native func
 v4 = "object"                     //BYTECODE_POS: 450 
 v3 = v3 === v4                    //BYTECODE_POS: 452 
 // if (!v3) skip to 463           //BYTECODE_POS: 453 
 v3 = ""                           //BYTECODE_POS: 455 
 v4 = navigator                    //BYTECODE_POS: 457 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.languages;                //BYTECODE_POS: 459 
 v3 += v4                          //BYTECODE_POS: 461 
 // go foward to 465               //BYTECODE_POS: 462 
 v4 = ""                           //BYTECODE_POS: 464 
 v3.languages = v3;                //BYTECODE_POS: 466 
 v3 = executionStack[2];           //BYTECODE_POS: 468 depth
 v3 = v3.navigator;                //BYTECODE_POS: 471 
 v4 = navigator                    //BYTECODE_POS: 473 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.onLine;                   //BYTECODE_POS: 475 
 // if (!v4) skip to 487           //BYTECODE_POS: 477 
 v4 = navigator                    //BYTECODE_POS: 479 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.onLine;                   //BYTECODE_POS: 481 
 v5 = ""                           //BYTECODE_POS: 483 
 v4 += v5                          //BYTECODE_POS: 485 
 // go foward to 489               //BYTECODE_POS: 486 
 v5 = ""                           //BYTECODE_POS: 488 
 v4.online = v4;                   //BYTECODE_POS: 490 
 // go foward to 515               //BYTECODE_POS: 492 
 executionStack[4] = v3;           //BYTECODE_POS: 494 // depth = 0
 v3 = executionStack[11];          //BYTECODE_POS: 497 depth
 v4 = v3                           //BYTECODE_POS: 500 
 v4 = v4.push;                     //BYTECODE_POS: 501 
 v5 = {};                          //BYTECODE_POS: 503 
 v6 = executionStack[4];           //BYTECODE_POS: 504 depth
 v5.err = v6;                      //BYTECODE_POS: 507 
 v6 = "d_n"                        //BYTECODE_POS: 509 
 v5.type = v6;                     //BYTECODE_POS: 511 
 v3 = v4(v5);                      //BYTECODE_POS: 513 // context 3 could be custom vm or native func
 v3 = document                     //BYTECODE_POS: 516 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v3                           //BYTECODE_POS: 518 
 v4 = v4.createEvent;              //BYTECODE_POS: 519 
 v5 = "TouchEvent"                 //BYTECODE_POS: 521 
 v3 = v4(v5);                      //BYTECODE_POS: 523 // context 3 could be custom vm or native func
 v3 = 1;                           //BYTECODE_POS: 526 
 executionStack[2] = v3;           //BYTECODE_POS: 528 // depth = 0
 // go foward to 540               //BYTECODE_POS: 531 
 executionStack[5] = v2;           //BYTECODE_POS: 533 // depth = 0
 v2 = 2;                           //BYTECODE_POS: 536 
 executionStack[2] = v2;           //BYTECODE_POS: 538 // depth = 0
 v2 = executionStack[2];           //BYTECODE_POS: 541 depth
 v2 = v2.navigator;                //BYTECODE_POS: 544 
 v3 = executionStack[2];           //BYTECODE_POS: 546 depth
 v2.touchEvent = v2;               //BYTECODE_POS: 549 
 v2 = "ontouchstart"               //BYTECODE_POS: 551 
 v3 = window                       //BYTECODE_POS: 553 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2 in v3                     //BYTECODE_POS: 555 
 // if (!v2) skip to 561           //BYTECODE_POS: 556 
 v2 = 1;                           //BYTECODE_POS: 558 
 // go foward to 563               //BYTECODE_POS: 560 
 v3 = 2;                           //BYTECODE_POS: 562 
 executionStack[3] = v3;           //BYTECODE_POS: 564 // depth = 0
 v3 = executionStack[2];           //BYTECODE_POS: 567 depth
 v3 = v3.navigator;                //BYTECODE_POS: 570 
 v4 = executionStack[3];           //BYTECODE_POS: 572 depth
 v3.touchstart = v3;               //BYTECODE_POS: 575 
 v3 = undefined                    //BYTECODE_POS: 577 
 //return v3;                      //BYTECODE_POS: 578 
}