function VM142() {
 var v0,v1,v2,v3,v4; // BYTECODE_POS: GENERATED
 var executionStack = [];          //BYTECODE_POS: GENEREATED 
 v0 = document                     //BYTECODE_POS: 1 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v1 = v0                           //BYTECODE_POS: 3 
 v1 = v1.createElement;            //BYTECODE_POS: 4 
 v2 = "canvas"                     //BYTECODE_POS: 6 
 v0 = v1(v2);                      //BYTECODE_POS: 8 // context 0 could be custom vm or native func
 executionStack[2] = v0;           //BYTECODE_POS: 10 // depth = 0
 v0 = HTMLCanvasElement            //BYTECODE_POS: 13 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v0.prototype;                //BYTECODE_POS: 15 
 executionStack[3] = v0;           //BYTECODE_POS: 17 // depth = 0
 v0 = CanvasRenderingContext2D     //BYTECODE_POS: 20 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v0.prototype;                //BYTECODE_POS: 22 
 executionStack[4] = v0;           //BYTECODE_POS: 24 // depth = 0
 v0 = executionStack[2];           //BYTECODE_POS: 27 depth
 v1 = v0                           //BYTECODE_POS: 30 
 v1 = v1.getContext;               //BYTECODE_POS: 31 
 v2 = "2d"                         //BYTECODE_POS: 33 
 v0 = v1(v2);                      //BYTECODE_POS: 35 // context 0 could be custom vm or native func
 executionStack[5] = v0;           //BYTECODE_POS: 37 // depth = 0
 v0 = {};                          //BYTECODE_POS: 40 
 v1 = ""                           //BYTECODE_POS: 41 
 v2 = undefined                    //BYTECODE_POS: 43 
 v3 = executionStack[4];           //BYTECODE_POS: 44 depth
 v4 = executionStack[2];           //BYTECODE_POS: 47 depth
 v4 = v4.toDataURL;                //BYTECODE_POS: 50 
 v5 = executionStack[3];           //BYTECODE_POS: 52 depth
 v5 = v5.toDataURL;                //BYTECODE_POS: 55 
 v2 = v3(v4,v5);                   //BYTECODE_POS: 57 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 59 
 v2 = undefined                    //BYTECODE_POS: 60 
 v3 = executionStack[3];           //BYTECODE_POS: 61 depth
 v4 = executionStack[2];           //BYTECODE_POS: 64 depth
 v4 = v4.toDataURL;                //BYTECODE_POS: 67 
 v2 = v3(v4);                      //BYTECODE_POS: 69 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 71 
 v2 = undefined                    //BYTECODE_POS: 72 
 v3 = executionStack[3];           //BYTECODE_POS: 73 depth
 v4 = executionStack[3];           //BYTECODE_POS: 76 depth
 v4 = v4.toDataURL;                //BYTECODE_POS: 79 
 v2 = v3(v4);                      //BYTECODE_POS: 81 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 83 
 v2 = undefined                    //BYTECODE_POS: 84 
 v3 = executionStack[4];           //BYTECODE_POS: 85 depth
 v4 = executionStack[2];           //BYTECODE_POS: 88 depth
 v4 = v4.getContext;               //BYTECODE_POS: 91 
 v5 = executionStack[3];           //BYTECODE_POS: 93 depth
 v5 = v5.getContext;               //BYTECODE_POS: 96 
 v2 = v3(v4,v5);                   //BYTECODE_POS: 98 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 100 
 v2 = undefined                    //BYTECODE_POS: 101 
 v3 = executionStack[3];           //BYTECODE_POS: 102 depth
 v4 = executionStack[2];           //BYTECODE_POS: 105 depth
 v4 = v4.getContext;               //BYTECODE_POS: 108 
 v2 = v3(v4);                      //BYTECODE_POS: 110 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 112 
 v2 = undefined                    //BYTECODE_POS: 113 
 v3 = executionStack[3];           //BYTECODE_POS: 114 depth
 v4 = executionStack[3];           //BYTECODE_POS: 117 depth
 v4 = v4.getContext;               //BYTECODE_POS: 120 
 v2 = v3(v4);                      //BYTECODE_POS: 122 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 124 
 v2 = undefined                    //BYTECODE_POS: 125 
 v3 = executionStack[4];           //BYTECODE_POS: 126 depth
 v4 = executionStack[5];           //BYTECODE_POS: 129 depth
 v4 = v4.getImageData;             //BYTECODE_POS: 132 
 v5 = executionStack[4];           //BYTECODE_POS: 134 depth
 v5 = v5.getImageData;             //BYTECODE_POS: 137 
 v2 = v3(v4,v5);                   //BYTECODE_POS: 139 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 141 
 v2 = undefined                    //BYTECODE_POS: 142 
 v3 = executionStack[3];           //BYTECODE_POS: 143 depth
 v4 = executionStack[5];           //BYTECODE_POS: 146 depth
 v4 = v4.getImageData;             //BYTECODE_POS: 149 
 v2 = v3(v4);                      //BYTECODE_POS: 151 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 153 
 v2 = undefined                    //BYTECODE_POS: 154 
 v3 = executionStack[3];           //BYTECODE_POS: 155 depth
 v4 = executionStack[4];           //BYTECODE_POS: 158 depth
 v4 = v4.getImageData;             //BYTECODE_POS: 161 
 v2 = v3(v4);                      //BYTECODE_POS: 163 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 165 
 v2 = undefined                    //BYTECODE_POS: 166 
 v3 = executionStack[4];           //BYTECODE_POS: 167 depth
 v4 = navigator                    //BYTECODE_POS: 170 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.toString;                 //BYTECODE_POS: 172 
 v5 = Navigator                    //BYTECODE_POS: 174 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v5 = v5.prototype;                //BYTECODE_POS: 176 
 v5 = v5.toString;                 //BYTECODE_POS: 178 
 v2 = v3(v4,v5);                   //BYTECODE_POS: 180 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 182 
 v2 = undefined                    //BYTECODE_POS: 183 
 v3 = executionStack[3];           //BYTECODE_POS: 184 depth
 v4 = navigator                    //BYTECODE_POS: 187 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.toString;                 //BYTECODE_POS: 189 
 v2 = v3(v4);                      //BYTECODE_POS: 191 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 193 
 v2 = undefined                    //BYTECODE_POS: 194 
 v3 = executionStack[3];           //BYTECODE_POS: 195 depth
 v4 = Navigator                    //BYTECODE_POS: 198 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.prototype;                //BYTECODE_POS: 200 
 v4 = v4.toString;                 //BYTECODE_POS: 202 
 v2 = v3(v4);                      //BYTECODE_POS: 204 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 206 
 v2 = undefined                    //BYTECODE_POS: 207 
 v3 = executionStack[3];           //BYTECODE_POS: 208 depth
 v4 = document                     //BYTECODE_POS: 211 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.createElement;            //BYTECODE_POS: 213 
 v2 = v3(v4);                      //BYTECODE_POS: 215 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 217 
 v2 = undefined                    //BYTECODE_POS: 218 
 v3 = executionStack[3];           //BYTECODE_POS: 219 depth
 v4 = document                     //BYTECODE_POS: 222 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.getElementById;           //BYTECODE_POS: 224 
 v2 = v3(v4);                      //BYTECODE_POS: 226 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 228 
 v2 = undefined                    //BYTECODE_POS: 229 
 v3 = executionStack[3];           //BYTECODE_POS: 230 depth
 v4 = JSON                         //BYTECODE_POS: 233 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.stringify;                //BYTECODE_POS: 235 
 v2 = v3(v4);                      //BYTECODE_POS: 237 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 239 
 v2 = undefined                    //BYTECODE_POS: 240 
 v3 = executionStack[3];           //BYTECODE_POS: 241 depth
 v4 = JSON                         //BYTECODE_POS: 244 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.parse;                    //BYTECODE_POS: 246 
 v2 = v3(v4);                      //BYTECODE_POS: 248 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 250 
 v2 = undefined                    //BYTECODE_POS: 251 
 v3 = executionStack[3];           //BYTECODE_POS: 252 depth
 v4 = window                       //BYTECODE_POS: 255 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.setInterval;              //BYTECODE_POS: 257 
 v2 = v3(v4);                      //BYTECODE_POS: 259 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 261 
 v2 = undefined                    //BYTECODE_POS: 262 
 v3 = executionStack[3];           //BYTECODE_POS: 263 depth
 v4 = window                       //BYTECODE_POS: 266 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.eval;                     //BYTECODE_POS: 268 
 v2 = v3(v4);                      //BYTECODE_POS: 270 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 272 
 v2 = undefined                    //BYTECODE_POS: 273 
 v3 = executionStack[3];           //BYTECODE_POS: 274 depth
 v4 = window                       //BYTECODE_POS: 277 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.matchMedia;               //BYTECODE_POS: 279 
 v2 = v3(v4);                      //BYTECODE_POS: 281 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 283 
 v2 = undefined                    //BYTECODE_POS: 284 
 v3 = executionStack[3];           //BYTECODE_POS: 285 depth
 v4 = Object                       //BYTECODE_POS: 288 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.getOwnPropertyNames;      //BYTECODE_POS: 290 
 v2 = v3(v4);                      //BYTECODE_POS: 292 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 294 
 v2 = undefined                    //BYTECODE_POS: 295 
 v3 = executionStack[4];           //BYTECODE_POS: 296 depth
 v4 = Function                     //BYTECODE_POS: 299 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.toString;                 //BYTECODE_POS: 301 
 v5 = executionStack[2];           //BYTECODE_POS: 303 depth
 v2 = v3(v4,v5);                   //BYTECODE_POS: 306 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 308 
 v2 = undefined                    //BYTECODE_POS: 309 
 v3 = executionStack[3];           //BYTECODE_POS: 310 depth
 v4 = Function                     //BYTECODE_POS: 313 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v4 = v4.toString;                 //BYTECODE_POS: 315 
 v2 = v3(v4);                      //BYTECODE_POS: 317 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 319 
 v2 = undefined                    //BYTECODE_POS: 320 
 v3 = executionStack[3];           //BYTECODE_POS: 321 depth
 v4 = executionStack[2];           //BYTECODE_POS: 324 depth
 v2 = v3(v4);                      //BYTECODE_POS: 327 // context 2 could be custom vm or native func
 v1 += v2                          //BYTECODE_POS: 329 
 v0.data = v1;                     //BYTECODE_POS: 330 
 //return v0;                      //BYTECODE_POS: 332 
}