function VM15() {
 var v0,v1,v2; // BYTECODE_POS: GENERATED
 var executionStack = [];          //BYTECODE_POS: GENEREATED 
 v0 = executionStack[2];           //BYTECODE_POS: 1 depth
 v0 = v0.window;                   //BYTECODE_POS: 4 
 v1 = undefined                    //BYTECODE_POS: 6 
 v2 = executionStack[14];          //BYTECODE_POS: 7 depth
 v3 = window                       //BYTECODE_POS: 10 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.Image;                    //BYTECODE_POS: 12 
 v1 = v2(v3);                      //BYTECODE_POS: 14 // context 1 could be custom vm or native func
 v0.Image = v0;                    //BYTECODE_POS: 16 
 v0 = executionStack[2];           //BYTECODE_POS: 18 depth
 v0 = v0.window;                   //BYTECODE_POS: 21 
 v1 = undefined                    //BYTECODE_POS: 23 
 v2 = executionStack[14];          //BYTECODE_POS: 24 depth
 v3 = window                       //BYTECODE_POS: 27 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.isSecureContext;          //BYTECODE_POS: 29 
 v1 = v2(v3);                      //BYTECODE_POS: 31 // context 1 could be custom vm or native func
 v0.isSecureContext = v0;          //BYTECODE_POS: 33 
 v0 = executionStack[2];           //BYTECODE_POS: 35 depth
 v0 = v0.window;                   //BYTECODE_POS: 38 
 v1 = undefined                    //BYTECODE_POS: 40 
 v2 = executionStack[14];          //BYTECODE_POS: 41 depth
 v3 = window                       //BYTECODE_POS: 44 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.ActiveXObject;            //BYTECODE_POS: 46 
 v1 = v2(v3);                      //BYTECODE_POS: 48 // context 1 could be custom vm or native func
 v0.ActiveXObject = v0;            //BYTECODE_POS: 50 
 v0 = executionStack[2];           //BYTECODE_POS: 52 depth
 v0 = v0.window;                   //BYTECODE_POS: 55 
 v1 = undefined                    //BYTECODE_POS: 57 
 v2 = executionStack[14];          //BYTECODE_POS: 58 depth
 v3 = window                       //BYTECODE_POS: 61 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.toolbar;                  //BYTECODE_POS: 63 
 v1 = v2(v3);                      //BYTECODE_POS: 65 // context 1 could be custom vm or native func
 v0.toolbar = v0;                  //BYTECODE_POS: 67 
 v0 = executionStack[2];           //BYTECODE_POS: 69 depth
 v0 = v0.window;                   //BYTECODE_POS: 72 
 v1 = undefined                    //BYTECODE_POS: 74 
 v2 = executionStack[14];          //BYTECODE_POS: 75 depth
 v3 = window                       //BYTECODE_POS: 78 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.locationbar;              //BYTECODE_POS: 80 
 v1 = v2(v3);                      //BYTECODE_POS: 82 // context 1 could be custom vm or native func
 v0.locationbar = v0;              //BYTECODE_POS: 84 
 v0 = executionStack[2];           //BYTECODE_POS: 86 depth
 v0 = v0.window;                   //BYTECODE_POS: 89 
 v1 = undefined                    //BYTECODE_POS: 91 
 v2 = executionStack[14];          //BYTECODE_POS: 92 depth
 v3 = window                       //BYTECODE_POS: 95 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.external;                 //BYTECODE_POS: 97 
 v1 = v2(v3);                      //BYTECODE_POS: 99 // context 1 could be custom vm or native func
 v0.external = v0;                 //BYTECODE_POS: 101 
 v0 = executionStack[2];           //BYTECODE_POS: 103 depth
 v0 = v0.window;                   //BYTECODE_POS: 106 
 v1 = undefined                    //BYTECODE_POS: 108 
 v2 = executionStack[14];          //BYTECODE_POS: 109 depth
 v3 = window                       //BYTECODE_POS: 112 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.mozRTCPeerConnection;     //BYTECODE_POS: 114 
 v1 = v2(v3);                      //BYTECODE_POS: 116 // context 1 could be custom vm or native func
 v0.mozRTCPeerConnection = v0;     //BYTECODE_POS: 118 
 v0 = executionStack[2];           //BYTECODE_POS: 120 depth
 v0 = v0.window;                   //BYTECODE_POS: 123 
 v1 = undefined                    //BYTECODE_POS: 125 
 v2 = executionStack[14];          //BYTECODE_POS: 126 depth
 v3 = window                       //BYTECODE_POS: 129 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.postMessage;              //BYTECODE_POS: 131 
 v1 = v2(v3);                      //BYTECODE_POS: 133 // context 1 could be custom vm or native func
 v0.postMessage = v0;              //BYTECODE_POS: 135 
 v0 = executionStack[2];           //BYTECODE_POS: 137 depth
 v0 = v0.window;                   //BYTECODE_POS: 140 
 v1 = undefined                    //BYTECODE_POS: 142 
 v2 = executionStack[14];          //BYTECODE_POS: 143 depth
 v3 = window                       //BYTECODE_POS: 146 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.webkitRequestAnimationFrame;//BYTECODE_POS: 148 
 v1 = v2(v3);                      //BYTECODE_POS: 150 // context 1 could be custom vm or native func
 v0.webkitRequestAnimationFrame = v0;//BYTECODE_POS: 152 
 v0 = executionStack[2];           //BYTECODE_POS: 154 depth
 v0 = v0.window;                   //BYTECODE_POS: 157 
 v1 = undefined                    //BYTECODE_POS: 159 
 v2 = executionStack[14];          //BYTECODE_POS: 160 depth
 v3 = window                       //BYTECODE_POS: 163 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.BluetoothUUID;            //BYTECODE_POS: 165 
 v1 = v2(v3);                      //BYTECODE_POS: 167 // context 1 could be custom vm or native func
 v0.BluetoothUUID = v0;            //BYTECODE_POS: 169 
 v0 = executionStack[2];           //BYTECODE_POS: 171 depth
 v0 = v0.window;                   //BYTECODE_POS: 174 
 v1 = undefined                    //BYTECODE_POS: 176 
 v2 = executionStack[14];          //BYTECODE_POS: 177 depth
 v3 = window                       //BYTECODE_POS: 180 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.netscape;                 //BYTECODE_POS: 182 
 v1 = v2(v3);                      //BYTECODE_POS: 184 // context 1 could be custom vm or native func
 v0.netscape = v0;                 //BYTECODE_POS: 186 
 v0 = executionStack[2];           //BYTECODE_POS: 188 depth
 v0 = v0.window;                   //BYTECODE_POS: 191 
 v1 = undefined                    //BYTECODE_POS: 193 
 v2 = executionStack[14];          //BYTECODE_POS: 194 depth
 v3 = window                       //BYTECODE_POS: 197 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.localStorage;             //BYTECODE_POS: 199 
 v1 = v2(v3);                      //BYTECODE_POS: 201 // context 1 could be custom vm or native func
 v0.localStorage = v0;             //BYTECODE_POS: 203 
 v0 = executionStack[2];           //BYTECODE_POS: 205 depth
 v0 = v0.window;                   //BYTECODE_POS: 208 
 v1 = undefined                    //BYTECODE_POS: 210 
 v2 = executionStack[14];          //BYTECODE_POS: 211 depth
 v3 = window                       //BYTECODE_POS: 214 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.sessionStorage;           //BYTECODE_POS: 216 
 v1 = v2(v3);                      //BYTECODE_POS: 218 // context 1 could be custom vm or native func
 v0.sessionStorage = v0;           //BYTECODE_POS: 220 
 v0 = executionStack[2];           //BYTECODE_POS: 222 depth
 v0 = v0.window;                   //BYTECODE_POS: 225 
 v1 = undefined                    //BYTECODE_POS: 227 
 v2 = executionStack[14];          //BYTECODE_POS: 228 depth
 v3 = window                       //BYTECODE_POS: 231 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.indexedDB;                //BYTECODE_POS: 233 
 v1 = v2(v3);                      //BYTECODE_POS: 235 // context 1 could be custom vm or native func
 v0.indexedDB = v0;                //BYTECODE_POS: 237 
 v0 = executionStack[2];           //BYTECODE_POS: 239 depth
 v0 = v0.window;                   //BYTECODE_POS: 242 
 v1 = window                       //BYTECODE_POS: 244 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v1 = v1.devicePixelRatio;         //BYTECODE_POS: 246 
 v1 = typeof v1;                   //BYTECODE_POS: 248 
 v2 = "number"                     //BYTECODE_POS: 249 
 v1 = v1 === v2                    //BYTECODE_POS: 251 
 // if (!v1) skip to 266           //BYTECODE_POS: 252 
 v1 = Math                         //BYTECODE_POS: 254 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v1                           //BYTECODE_POS: 256 
 v2 = v2.floor;                    //BYTECODE_POS: 257 
 v3 = window                       //BYTECODE_POS: 259 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.devicePixelRatio;         //BYTECODE_POS: 261 
 v1 = v2(v3);                      //BYTECODE_POS: 263 // context 1 could be custom vm or native func
 // go foward to 269               //BYTECODE_POS: 265 
 v2 = 1;                           //BYTECODE_POS: 267 
 v2 = -v2                          //BYTECODE_POS: 269 
 v1.devicePixelRatio = v1;         //BYTECODE_POS: 270 
 v1 = executionStack[2];           //BYTECODE_POS: 272 depth
 v1 = v1.window;                   //BYTECODE_POS: 275 
 v2 = window                       //BYTECODE_POS: 277 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.devicePixelRatio;         //BYTECODE_POS: 279 
 v1.devicePixelRatioFloat = v1;    //BYTECODE_POS: 281 
 v1 = executionStack[2];           //BYTECODE_POS: 283 depth
 v1 = v1.window;                   //BYTECODE_POS: 286 
 v2 = window                       //BYTECODE_POS: 288 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.location;                 //BYTECODE_POS: 290 
 v2 = v2.href;                     //BYTECODE_POS: 292 
 v1.location = v1;                 //BYTECODE_POS: 294 
 // go foward to 319               //BYTECODE_POS: 296 
 executionStack[2] = v0;           //BYTECODE_POS: 298 // depth = 0
 v0 = executionStack[11];          //BYTECODE_POS: 301 depth
 v1 = v0                           //BYTECODE_POS: 304 
 v1 = v1.push;                     //BYTECODE_POS: 305 
 v2 = {};                          //BYTECODE_POS: 307 
 v3 = executionStack[2];           //BYTECODE_POS: 308 depth
 v2.err = v3;                      //BYTECODE_POS: 311 
 v3 = "d_w"                        //BYTECODE_POS: 313 
 v2.type = v3;                     //BYTECODE_POS: 315 
 v0 = v1(v2);                      //BYTECODE_POS: 317 // context 0 could be custom vm or native func
 v0 = undefined                    //BYTECODE_POS: 320 
 //return v0;                      //BYTECODE_POS: 321 
}