function VM184() {
 var v0,v1; // BYTECODE_POS: GENERATED
 var executionStack = [];          //BYTECODE_POS: GENEREATED 
 v0 = performance                  //BYTECODE_POS: 1 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v0.timing;                   //BYTECODE_POS: 3 
 executionStack[2] = v0;           //BYTECODE_POS: 5 // depth = 0
 v0 = {};                          //BYTECODE_POS: 8 
 v1 = ""                           //BYTECODE_POS: 9 
 v2 = executionStack[2];           //BYTECODE_POS: 11 depth
 v2 = v2.connectEnd;               //BYTECODE_POS: 14 
 v1 += v2                          //BYTECODE_POS: 16 
 v0.cE = v1;                       //BYTECODE_POS: 17 
 v1 = ""                           //BYTECODE_POS: 19 
 v2 = executionStack[2];           //BYTECODE_POS: 21 depth
 v2 = v2.connectStart;             //BYTECODE_POS: 24 
 v1 += v2                          //BYTECODE_POS: 26 
 v0.cS = v1;                       //BYTECODE_POS: 27 
 v1 = ""                           //BYTECODE_POS: 29 
 v2 = executionStack[2];           //BYTECODE_POS: 31 depth
 v2 = v2.domComplete;              //BYTECODE_POS: 34 
 v1 += v2                          //BYTECODE_POS: 36 
 v0.dC = v1;                       //BYTECODE_POS: 37 
 v1 = ""                           //BYTECODE_POS: 39 
 v2 = executionStack[2];           //BYTECODE_POS: 41 depth
 v2 = v2.domContentLoadedEventEnd; //BYTECODE_POS: 44 
 v1 += v2                          //BYTECODE_POS: 46 
 v0.dCEE = v1;                     //BYTECODE_POS: 47 
 v1 = ""                           //BYTECODE_POS: 49 
 v2 = executionStack[2];           //BYTECODE_POS: 51 depth
 v2 = v2.domContentLoadedEventStart;//BYTECODE_POS: 54 
 v1 += v2                          //BYTECODE_POS: 56 
 v0.dCES = v1;                     //BYTECODE_POS: 57 
 v1 = ""                           //BYTECODE_POS: 59 
 v2 = executionStack[2];           //BYTECODE_POS: 61 depth
 v2 = v2.domInteractive;           //BYTECODE_POS: 64 
 v1 += v2                          //BYTECODE_POS: 66 
 v0.dI = v1;                       //BYTECODE_POS: 67 
 v1 = ""                           //BYTECODE_POS: 69 
 v2 = executionStack[2];           //BYTECODE_POS: 71 depth
 v2 = v2.domLoading;               //BYTECODE_POS: 74 
 v1 += v2                          //BYTECODE_POS: 76 
 v0.dL = v1;                       //BYTECODE_POS: 77 
 v1 = ""                           //BYTECODE_POS: 79 
 v2 = executionStack[2];           //BYTECODE_POS: 81 depth
 v2 = v2.domainLookupEnd;          //BYTECODE_POS: 84 
 v1 += v2                          //BYTECODE_POS: 86 
 v0.dLE = v1;                      //BYTECODE_POS: 87 
 v1 = ""                           //BYTECODE_POS: 89 
 v2 = executionStack[2];           //BYTECODE_POS: 91 depth
 v2 = v2.domainLookupStart;        //BYTECODE_POS: 94 
 v1 += v2                          //BYTECODE_POS: 96 
 v0.dLS = v1;                      //BYTECODE_POS: 97 
 v1 = ""                           //BYTECODE_POS: 99 
 v2 = executionStack[2];           //BYTECODE_POS: 101 depth
 v2 = v2.fetchStart;               //BYTECODE_POS: 104 
 v1 += v2                          //BYTECODE_POS: 106 
 v0.fS = v1;                       //BYTECODE_POS: 107 
 v1 = ""                           //BYTECODE_POS: 109 
 v2 = executionStack[2];           //BYTECODE_POS: 111 depth
 v2 = v2.loadEventEnd;             //BYTECODE_POS: 114 
 v1 += v2                          //BYTECODE_POS: 116 
 v0.lEE = v1;                      //BYTECODE_POS: 117 
 v1 = ""                           //BYTECODE_POS: 119 
 v2 = executionStack[2];           //BYTECODE_POS: 121 depth
 v2 = v2.loadEventStart;           //BYTECODE_POS: 124 
 v1 += v2                          //BYTECODE_POS: 126 
 v0.lES = v1;                      //BYTECODE_POS: 127 
 v1 = ""                           //BYTECODE_POS: 129 
 v2 = executionStack[2];           //BYTECODE_POS: 131 depth
 v2 = v2.navigationStart;          //BYTECODE_POS: 134 
 v1 += v2                          //BYTECODE_POS: 136 
 v0.nS = v1;                       //BYTECODE_POS: 137 
 v1 = ""                           //BYTECODE_POS: 139 
 v2 = executionStack[2];           //BYTECODE_POS: 141 depth
 v2 = v2.redirectEnd;              //BYTECODE_POS: 144 
 v1 += v2                          //BYTECODE_POS: 146 
 v0.rE = v1;                       //BYTECODE_POS: 147 
 v1 = ""                           //BYTECODE_POS: 149 
 v2 = executionStack[2];           //BYTECODE_POS: 151 depth
 v2 = v2.redirectStart;            //BYTECODE_POS: 154 
 v1 += v2                          //BYTECODE_POS: 156 
 v0.rS = v1;                       //BYTECODE_POS: 157 
 v1 = ""                           //BYTECODE_POS: 159 
 v2 = executionStack[2];           //BYTECODE_POS: 161 depth
 v2 = v2.requestStart;             //BYTECODE_POS: 164 
 v1 += v2                          //BYTECODE_POS: 166 
 v0.reqS = v1;                     //BYTECODE_POS: 167 
 v1 = ""                           //BYTECODE_POS: 169 
 v2 = executionStack[2];           //BYTECODE_POS: 171 depth
 v2 = v2.responseEnd;              //BYTECODE_POS: 174 
 v1 += v2                          //BYTECODE_POS: 176 
 v0.resE = v1;                     //BYTECODE_POS: 177 
 v1 = ""                           //BYTECODE_POS: 179 
 v2 = executionStack[2];           //BYTECODE_POS: 181 depth
 v2 = v2.responseStart;            //BYTECODE_POS: 184 
 v1 += v2                          //BYTECODE_POS: 186 
 v0.resS = v1;                     //BYTECODE_POS: 187 
 v1 = ""                           //BYTECODE_POS: 189 
 v2 = executionStack[2];           //BYTECODE_POS: 191 depth
 v2 = v2.secureConnectionStart;    //BYTECODE_POS: 194 
 v1 += v2                          //BYTECODE_POS: 196 
 v0.sCS = v1;                      //BYTECODE_POS: 197 
 v1 = ""                           //BYTECODE_POS: 199 
 v2 = executionStack[2];           //BYTECODE_POS: 201 depth
 v2 = v2.unloadEventEnd;           //BYTECODE_POS: 204 
 v1 += v2                          //BYTECODE_POS: 206 
 v0.uEE = v1;                      //BYTECODE_POS: 207 
 v1 = ""                           //BYTECODE_POS: 209 
 v2 = executionStack[2];           //BYTECODE_POS: 211 depth
 v2 = v2.unloadEventStart;         //BYTECODE_POS: 214 
 v1 += v2                          //BYTECODE_POS: 216 
 v0.uES = v1;                      //BYTECODE_POS: 217 
 executionStack[3] = v0;           //BYTECODE_POS: 219 // depth = 0
 v0 = {};                          //BYTECODE_POS: 222 
 v1 = executionStack[3];           //BYTECODE_POS: 223 depth
 v0.data = v1;                     //BYTECODE_POS: 226 
 //return v0;                      //BYTECODE_POS: 228 
}