function VM182() {
 var v0,v1,v2; // BYTECODE_POS: GENERATED
 var executionStack = [];          //BYTECODE_POS: GENEREATED 
 v0 = document                     //BYTECODE_POS: 1 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v1 = v0                           //BYTECODE_POS: 3 
 v1 = v1.createElement;            //BYTECODE_POS: 4 
 v2 = "iframe"                     //BYTECODE_POS: 6 
 v0 = v1(v2);                      //BYTECODE_POS: 8 // context 0 could be custom vm or native func
 executionStack[2] = v0;           //BYTECODE_POS: 10 // depth = 0
 v0 = executionStack[2];           //BYTECODE_POS: 13 depth
 v0 = v0.style;                    //BYTECODE_POS: 16 
 v1 = "none"                       //BYTECODE_POS: 18 
 v0.display = v0;                  //BYTECODE_POS: 20 
 v0 = document                     //BYTECODE_POS: 22 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v0.body;                     //BYTECODE_POS: 24 
 v1 = v0                           //BYTECODE_POS: 26 
 v1 = v1.appendChild;              //BYTECODE_POS: 27 
 v2 = executionStack[2];           //BYTECODE_POS: 29 depth
 v0 = v1(v2);                      //BYTECODE_POS: 32 // context 0 could be custom vm or native func
 v0 = {};                          //BYTECODE_POS: 35 
 v1 = {};                          //BYTECODE_POS: 36 
 v0.iFrameNP = v1;                 //BYTECODE_POS: 37 
 v1 = {};                          //BYTECODE_POS: 39 
 v0.iFrameSP = v1;                 //BYTECODE_POS: 40 
 executionStack[3] = v0;           //BYTECODE_POS: 42 // depth = 0
 v0 = executionStack[3];           //BYTECODE_POS: 45 depth
 v0 = v0.iFrameNP;                 //BYTECODE_POS: 48 
 v1 = executionStack[2];           //BYTECODE_POS: 50 depth
 v1 = v1.contentWindow;            //BYTECODE_POS: 53 
 v1 = v1.navigator;                //BYTECODE_POS: 55 
 v1 = v1.userAgent;                //BYTECODE_POS: 57 
 v0.uA = v0;                       //BYTECODE_POS: 59 
 v0 = executionStack[3];           //BYTECODE_POS: 61 depth
 v0 = v0.iFrameNP;                 //BYTECODE_POS: 64 
 v1 = executionStack[2];           //BYTECODE_POS: 66 depth
 v1 = v1.contentWindow;            //BYTECODE_POS: 69 
 v1 = v1.navigator;                //BYTECODE_POS: 71 
 v1 = v1.platform;                 //BYTECODE_POS: 73 
 v0.platform = v0;                 //BYTECODE_POS: 75 
 v0 = executionStack[3];           //BYTECODE_POS: 77 depth
 v0 = v0.iFrameNP;                 //BYTECODE_POS: 80 
 v1 = executionStack[2];           //BYTECODE_POS: 82 depth
 v1 = v1.contentWindow;            //BYTECODE_POS: 85 
 v1 = v1.navigator;                //BYTECODE_POS: 87 
 v1 = v1.hardwareConcurrency;      //BYTECODE_POS: 89 
 v0.hC = v0;                       //BYTECODE_POS: 91 
 v0 = executionStack[3];           //BYTECODE_POS: 93 depth
 v0 = v0.iFrameNP;                 //BYTECODE_POS: 96 
 v1 = executionStack[2];           //BYTECODE_POS: 98 depth
 v1 = v1.contentWindow;            //BYTECODE_POS: 101 
 v1 = v1.navigator;                //BYTECODE_POS: 103 
 v1 = v1.language;                 //BYTECODE_POS: 105 
 v0.lang = v0;                     //BYTECODE_POS: 107 
 v0 = executionStack[3];           //BYTECODE_POS: 109 depth
 v0 = v0.iFrameNP;                 //BYTECODE_POS: 112 
 v1 = ""                           //BYTECODE_POS: 114 
 v2 = executionStack[2];           //BYTECODE_POS: 116 depth
 v2 = v2.contentWindow;            //BYTECODE_POS: 119 
 v2 = v2.navigator;                //BYTECODE_POS: 121 
 v2 = v2.webdriver;                //BYTECODE_POS: 123 
 v1 += v2                          //BYTECODE_POS: 125 
 v0.wd = v0;                       //BYTECODE_POS: 126 
 v0 = executionStack[3];           //BYTECODE_POS: 128 depth
 v0 = v0.iFrameSP;                 //BYTECODE_POS: 131 
 v1 = executionStack[2];           //BYTECODE_POS: 133 depth
 v1 = v1.contentWindow;            //BYTECODE_POS: 136 
 v1 = v1.screen;                   //BYTECODE_POS: 138 
 v1 = v1.availHeight;              //BYTECODE_POS: 140 
 v0.aH = v0;                       //BYTECODE_POS: 142 
 v0 = executionStack[3];           //BYTECODE_POS: 144 depth
 v0 = v0.iFrameSP;                 //BYTECODE_POS: 147 
 v1 = executionStack[2];           //BYTECODE_POS: 149 depth
 v1 = v1.contentWindow;            //BYTECODE_POS: 152 
 v1 = v1.screen;                   //BYTECODE_POS: 154 
 v1 = v1.availWidth;               //BYTECODE_POS: 156 
 v0.aW = v0;                       //BYTECODE_POS: 158 
 v0 = executionStack[3];           //BYTECODE_POS: 160 depth
 v0 = v0.iFrameSP;                 //BYTECODE_POS: 163 
 v1 = executionStack[2];           //BYTECODE_POS: 165 depth
 v1 = v1.contentWindow;            //BYTECODE_POS: 168 
 v1 = v1.screen;                   //BYTECODE_POS: 170 
 v1 = v1.height;                   //BYTECODE_POS: 172 
 v0.h = v0;                        //BYTECODE_POS: 174 
 v0 = executionStack[3];           //BYTECODE_POS: 176 depth
 v0 = v0.iFrameSP;                 //BYTECODE_POS: 179 
 v1 = executionStack[2];           //BYTECODE_POS: 181 depth
 v1 = v1.contentWindow;            //BYTECODE_POS: 184 
 v1 = v1.screen;                   //BYTECODE_POS: 186 
 v1 = v1.width;                    //BYTECODE_POS: 188 
 v0.w = v0;                        //BYTECODE_POS: 190 
 v0 = executionStack[3];           //BYTECODE_POS: 192 depth
 v0 = v0.iFrameSP;                 //BYTECODE_POS: 195 
 v1 = executionStack[2];           //BYTECODE_POS: 197 depth
 v1 = v1.contentWindow;            //BYTECODE_POS: 200 
 v1 = v1.screen;                   //BYTECODE_POS: 202 
 v1 = v1.pixelDepth;               //BYTECODE_POS: 204 
 v0.pD = v0;                       //BYTECODE_POS: 206 
 v0 = Object                       //BYTECODE_POS: 208 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v1 = v0                           //BYTECODE_POS: 210 
 v1 = v1.getOwnPropertyNames;      //BYTECODE_POS: 211 
 v2 = executionStack[2];           //BYTECODE_POS: 213 depth
 v2 = v2.contentWindow;            //BYTECODE_POS: 216 
 v0 = v1(v2);                      //BYTECODE_POS: 218 // context 0 could be custom vm or native func
 executionStack[4] = v0;           //BYTECODE_POS: 220 // depth = 0
 v0 = executionStack[3];           //BYTECODE_POS: 223 depth
 v1 = undefined                    //BYTECODE_POS: 226 
 v2 = executionStack[2];           //BYTECODE_POS: 227 depth
 v3 = executionStack[4];           //BYTECODE_POS: 230 depth
 v1 = v2(v3);                      //BYTECODE_POS: 233 // context 1 could be custom vm or native func
 v2 = v1                           //BYTECODE_POS: 235 
 v2 = v2.toString;                 //BYTECODE_POS: 236 
 v1 = v2();                        //BYTECODE_POS: 238 // context 1 could be custom vm or native func
 v0.propHash = v0;                 //BYTECODE_POS: 240 
 v0 = document                     //BYTECODE_POS: 242 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v0.body;                     //BYTECODE_POS: 244 
 v1 = v0                           //BYTECODE_POS: 246 
 v1 = v1.removeChild;              //BYTECODE_POS: 247 
 v2 = executionStack[2];           //BYTECODE_POS: 249 depth
 v0 = v1(v2);                      //BYTECODE_POS: 252 // context 0 could be custom vm or native func
 v0 = {};                          //BYTECODE_POS: 255 
 v1 = executionStack[3];           //BYTECODE_POS: 256 depth
 v0.data = v1;                     //BYTECODE_POS: 259 
 //return v0;                      //BYTECODE_POS: 261 
}