function VM39() {
 var v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16; // BYTECODE_POS: GENERATED
 var executionStack = [];          //BYTECODE_POS: GENEREATED 
 v0 = Date                         //BYTECODE_POS: 1 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = new v0()                     //BYTECODE_POS: 3 
 executionStack[2] = v0;           //BYTECODE_POS: 5 // depth = 0
 v0 = "XDomainRequest"             //BYTECODE_POS: 8 
 v1 = "createPopup"                //BYTECODE_POS: 10 
 v2 = "removeEventListener"        //BYTECODE_POS: 12 
 v3 = "globalStorage"              //BYTECODE_POS: 14 
 v4 = "openDatabase"               //BYTECODE_POS: 16 
 v5 = "indexedDB"                  //BYTECODE_POS: 18 
 v6 = "attachEvent"                //BYTECODE_POS: 20 
 v7 = "ActiveXObject"              //BYTECODE_POS: 22 
 v8 = "dispatchEvent"              //BYTECODE_POS: 24 
 v9 = "addBehavior"                //BYTECODE_POS: 26 
 v10 = "addEventListener"          //BYTECODE_POS: 28 
 v11 = "detachEvent"               //BYTECODE_POS: 30 
 v12 = "fireEvent"                 //BYTECODE_POS: 32 
 v13 = "MutationObserver"          //BYTECODE_POS: 34 
 v14 = "HTMLMenuItemElement"       //BYTECODE_POS: 36 
 v15 = "Int8Array"                 //BYTECODE_POS: 38 
 v16 = "postMessage"               //BYTECODE_POS: 40 
 v17 = "querySelector"             //BYTECODE_POS: 42 
 v0 = [v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17]//BYTECODE_POS: 44 
 executionStack[5] = v0;           //BYTECODE_POS: 46 // depth = 0
 v0 = undefined                    //BYTECODE_POS: 49 
 v1 = executionStack[24];          //BYTECODE_POS: 50 depth
 v2 = window                       //BYTECODE_POS: 53 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = executionStack[5];           //BYTECODE_POS: 55 depth
 v4 = 0;                           //BYTECODE_POS: 58 
 v0 = v1(v2,v3,v4);                //BYTECODE_POS: 60 // context 0 could be custom vm or native func
 executionStack[3] = v0;           //BYTECODE_POS: 62 // depth = 0
 v0 = executionStack[3];           //BYTECODE_POS: 65 depth
 v1 = undefined                    //BYTECODE_POS: 68 
 v2 = executionStack[24];          //BYTECODE_POS: 69 depth
 v3 = window                       //BYTECODE_POS: 72 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v3 = v3.performance;              //BYTECODE_POS: 74 
 v4 = "now"                        //BYTECODE_POS: 76 
 v4 = [v4]                         //BYTECODE_POS: 78 
 v5 = executionStack[5];           //BYTECODE_POS: 80 depth
 v5 = v5.length;                   //BYTECODE_POS: 83 
 v1 = v2(v3,v4,v5);                //BYTECODE_POS: 85 // context 1 could be custom vm or native func
 v0 |= v1;                         //BYTECODE_POS: 87 
 //get depth of 0 from executionStack//BYTECODE_POS: 88 
 v1 = executionStack;              //BYTECODE_POS: 88 
 v2 = 3                            //BYTECODE_POS: NO BYTECODE POS ADDED 
 v1[v2] = v0                       //BYTECODE_POS: 91 
 v0 = "contextMenu"                //BYTECODE_POS: 93 
 v0 = [v0]                         //BYTECODE_POS: 95 
 executionStack[6] = v0;           //BYTECODE_POS: 97 // depth = 0
 v0 = undefined                    //BYTECODE_POS: 100 
 v1 = executionStack[24];          //BYTECODE_POS: 101 depth
 v2 = document                     //BYTECODE_POS: 104 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v2 = v2.documentElement;          //BYTECODE_POS: 106 
 v3 = executionStack[6];           //BYTECODE_POS: 108 depth
 v4 = 0;                           //BYTECODE_POS: 111 
 v0 = v1(v2,v3,v4);                //BYTECODE_POS: 113 // context 0 could be custom vm or native func
 executionStack[4] = v0;           //BYTECODE_POS: 115 // depth = 0
 v0 = {};                          //BYTECODE_POS: 118 
 executionStack[7] = v0;           //BYTECODE_POS: 119 // depth = 0
 v0 = executionStack[7];           //BYTECODE_POS: 122 depth
 v1 = executionStack[28];          //BYTECODE_POS: 125 depth
 v2 = executionStack[29];          //BYTECODE_POS: 128 depth
 v1 = v1[v2]                       //BYTECODE_POS: 131 
 v0.nativeLength = v0;             //BYTECODE_POS: 132 
 v0 = executionStack[7];           //BYTECODE_POS: 134 depth
 v1 = executionStack[28];          //BYTECODE_POS: 137 depth
 v2 = executionStack[30];          //BYTECODE_POS: 140 depth
 v1 = v1[v2]                       //BYTECODE_POS: 143 
 v0.nativeName = v0;               //BYTECODE_POS: 144 
 v0 = executionStack[7];           //BYTECODE_POS: 146 depth
 v1 = executionStack[28];          //BYTECODE_POS: 149 depth
 v2 = executionStack[2];           //BYTECODE_POS: 152 depth
 v1 = v1[v2]                       //BYTECODE_POS: 155 
 v0.jsFontsList = v0;              //BYTECODE_POS: 156 
 // go foward to 181               //BYTECODE_POS: 158 
 executionStack[10] = v-1;         //BYTECODE_POS: 160 // depth = 0
 v-1 = executionStack[11];         //BYTECODE_POS: 163 depth
 v0 = v-1                          //BYTECODE_POS: 166 
 v0 = v0.push;                     //BYTECODE_POS: 167 
 v1 = {};                          //BYTECODE_POS: 169 
 v2 = executionStack[10];          //BYTECODE_POS: 170 depth
 v1.err = v2;                      //BYTECODE_POS: 173 
 v2 = "d_w_f"                      //BYTECODE_POS: 175 
 v1.type = v2;                     //BYTECODE_POS: 177 
 v-1 = v0(v1);                     //BYTECODE_POS: 179 // context -1 could be custom vm or native func
 v-1 = executionStack[7];          //BYTECODE_POS: 182 depth
 v0 = executionStack[28];          //BYTECODE_POS: 185 depth
 v1 = arguments;                   //BYTECODE_POS: 188 depth
 v0 = v0[v1]                       //BYTECODE_POS: 191 
 v-1.syntaxError = v-1;            //BYTECODE_POS: 192 
 v-1 = executionStack[7];          //BYTECODE_POS: 194 depth
 v0 = ""                           //BYTECODE_POS: 197 
 v1 = Date                         //BYTECODE_POS: 199 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v1 = new v1()                     //BYTECODE_POS: 201 
 v2 = v1                           //BYTECODE_POS: 203 
 v2 = v2.getTime;                  //BYTECODE_POS: 204 
 v1 = v2();                        //BYTECODE_POS: 206 // context 1 could be custom vm or native func
 v0 += v1                          //BYTECODE_POS: 208 
 v-1.timestamp = v-1;              //BYTECODE_POS: 209 
 v-1 = executionStack[7];          //BYTECODE_POS: 211 depth
 v0 = Math                         //BYTECODE_POS: 214 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v1 = v0                           //BYTECODE_POS: 216 
 v1 = v1.floor;                    //BYTECODE_POS: 217 
 v2 = executionStack[2];           //BYTECODE_POS: 219 depth
 v3 = v2                           //BYTECODE_POS: 222 
 v3 = v3.getTimezoneOffset;        //BYTECODE_POS: 223 
 v2 = v3();                        //BYTECODE_POS: 225 // context 2 could be custom vm or native func
 v2 = -v2                          //BYTECODE_POS: 227 
 v3 = 60;                          //BYTECODE_POS: 228 
 v2 /= v3                          //BYTECODE_POS: 230 
 v0 = v1(v2);                      //BYTECODE_POS: 231 // context 0 could be custom vm or native func
 v-1.timezone = v-1;               //BYTECODE_POS: 233 
 v-1 = executionStack[7];          //BYTECODE_POS: 235 depth
 v0 = executionStack[28];          //BYTECODE_POS: 238 depth
 v1 = executionStack[31];          //BYTECODE_POS: 241 depth
 v0 = v0[v1]                       //BYTECODE_POS: 244 
 v-1.magic = v-1;                  //BYTECODE_POS: 245 
 v-1 = executionStack[7];          //BYTECODE_POS: 247 depth
 v0 = executionStack[28];          //BYTECODE_POS: 250 depth
 v1 = executionStack[5];           //BYTECODE_POS: 253 depth
 v0 = v0[v1]                       //BYTECODE_POS: 256 
 v1 = ""                           //BYTECODE_POS: 257 
 v0 += v1                          //BYTECODE_POS: 259 
 v-1.canvas = v-1;                 //BYTECODE_POS: 260 
 v-1 = executionStack[7];          //BYTECODE_POS: 262 depth
 v0 = executionStack[28];          //BYTECODE_POS: 265 depth
 v1 = executionStack[32];          //BYTECODE_POS: 268 depth
 v0 = v0[v1]                       //BYTECODE_POS: 271 
 v-1.wProps = v-1;                 //BYTECODE_POS: 272 
 v-1 = executionStack[7];          //BYTECODE_POS: 274 depth
 v0 = executionStack[28];          //BYTECODE_POS: 277 depth
 v1 = executionStack[33];          //BYTECODE_POS: 280 depth
 v0 = v0[v1]                       //BYTECODE_POS: 283 
 v-1.dProps = v-1;                 //BYTECODE_POS: 284 
 v-1 = executionStack[7];          //BYTECODE_POS: 286 depth
 v0 = ""                           //BYTECODE_POS: 289 
 v-1.jsv = v-1;                    //BYTECODE_POS: 291 
 v-1 = executionStack[7];          //BYTECODE_POS: 293 depth
 v0 = executionStack[28];          //BYTECODE_POS: 296 depth
 v1 = executionStack[34];          //BYTECODE_POS: 299 depth
 v0 = v0[v1]                       //BYTECODE_POS: 302 
 v-1.browserType = v-1;            //BYTECODE_POS: 303 
 v-1 = executionStack[7];          //BYTECODE_POS: 305 depth
 v0 = executionStack[28];          //BYTECODE_POS: 308 depth
 v1 = executionStack[35];          //BYTECODE_POS: 311 depth
 v0 = v0[v1]                       //BYTECODE_POS: 314 
 v-1.iframe = v-1;                 //BYTECODE_POS: 315 
 v-1 = executionStack[7];          //BYTECODE_POS: 317 depth
 v0 = window                       //BYTECODE_POS: 320 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v0._mssdk;                   //BYTECODE_POS: 322 
 v0 = v0.pppt;                     //BYTECODE_POS: 324 
 v-1.pppt = v-1;                   //BYTECODE_POS: 326 
 v-1 = executionStack[7];          //BYTECODE_POS: 328 depth
 v0 = executionStack[28];          //BYTECODE_POS: 331 depth
 v1 = executionStack[36];          //BYTECODE_POS: 334 depth
 v0 = v0[v1]                       //BYTECODE_POS: 337 
 v-1.rtt = v-1;                    //BYTECODE_POS: 338 
 v-1 = executionStack[7];          //BYTECODE_POS: 340 depth
 v0 = executionStack[28];          //BYTECODE_POS: 343 depth
 v1 = executionStack[37];          //BYTECODE_POS: 346 depth
 v0 = v0[v1]                       //BYTECODE_POS: 349 
 v-1.notifyPerm = v-1;             //BYTECODE_POS: 350 
 v-1 = executionStack[7];          //BYTECODE_POS: 352 depth
 v0 = "5.0.2"                      //BYTECODE_POS: 355 
 v-1.sdkVersion = v-1;             //BYTECODE_POS: 357 
 v-1 = executionStack[7];          //BYTECODE_POS: 359 depth
 v0 = "1.0.0.223"                  //BYTECODE_POS: 362 
 v-1.scmVersion = v-1;             //BYTECODE_POS: 364 
 v-1 = 1;                          //BYTECODE_POS: 366 
 executionStack[8] = v-1;          //BYTECODE_POS: 368 // depth = 0
 v-1 = executionStack[7];          //BYTECODE_POS: 371 depth
 v0 = executionStack[10];          //BYTECODE_POS: 374 depth
 v0 = v0.aid;                      //BYTECODE_POS: 377 
 v-1.aid = v-1;                    //BYTECODE_POS: 379 
 v-1 = executionStack[7];          //BYTECODE_POS: 381 depth
 v0 = undefined                    //BYTECODE_POS: 384 
 v1 = executionStack[4];           //BYTECODE_POS: 385 depth
 v2 = "ttcid"                      //BYTECODE_POS: 388 
 v0 = v1(v2);                      //BYTECODE_POS: 390 // context 0 could be custom vm or native func
 v-1.client = v-1;                 //BYTECODE_POS: 392 
 v-1 = executionStack[7];          //BYTECODE_POS: 394 depth
 v0 = undefined                    //BYTECODE_POS: 397 
 v1 = executionStack[4];           //BYTECODE_POS: 398 depth
 v2 = "tt_scid"                    //BYTECODE_POS: 401 
 v0 = v1(v2);                      //BYTECODE_POS: 403 // context 0 could be custom vm or native func
 v-1.token = v-1;                  //BYTECODE_POS: 405 
 v-1 = executionStack[7];          //BYTECODE_POS: 407 depth
 v0 = executionStack[8];           //BYTECODE_POS: 410 depth
 v-1.msgType = v-1;                //BYTECODE_POS: 413 
 v-1 = executionStack[7];          //BYTECODE_POS: 415 depth
 v0 = undefined                    //BYTECODE_POS: 418 
 v1 = executionStack[21];          //BYTECODE_POS: 419 depth
 v0 = v1();                        //BYTECODE_POS: 422 // context 0 could be custom vm or native func
 v-1.privacyMode = v-1;            //BYTECODE_POS: 424 
 v-1 = executionStack[7];          //BYTECODE_POS: 426 depth
 v0 = executionStack[9];           //BYTECODE_POS: 429 depth
 v0 = v0.aidList;                  //BYTECODE_POS: 432 
 v-1.aidList = v-1;                //BYTECODE_POS: 434 
 v-1 = executionStack[7];          //BYTECODE_POS: 436 depth
 v0 = executionStack[28];          //BYTECODE_POS: 439 depth
 v1 = executionStack[38];          //BYTECODE_POS: 442 depth
 v0 = v0[v1]                       //BYTECODE_POS: 445 
 v-1.isf = v-1;                    //BYTECODE_POS: 446 
 v-1 = executionStack[7];          //BYTECODE_POS: 448 depth
 v0 = executionStack[28];          //BYTECODE_POS: 451 depth
 v1 = executionStack[17];          //BYTECODE_POS: 454 depth
 v0 = v0[v1]                       //BYTECODE_POS: 457 
 v-1.env = v-1;                    //BYTECODE_POS: 458 
 v-1 = executionStack[7];          //BYTECODE_POS: 460 depth
 v0 = executionStack[28];          //BYTECODE_POS: 463 depth
 v1 = executionStack[23];          //BYTECODE_POS: 466 depth
 v0 = v0[v1]                       //BYTECODE_POS: 469 
 v-1.propLength = v-1;             //BYTECODE_POS: 470 
 v-1 = executionStack[7];          //BYTECODE_POS: 472 depth
 v0 = executionStack[28];          //BYTECODE_POS: 475 depth
 v1 = executionStack[18];          //BYTECODE_POS: 478 depth
 v0 = v0[v1]                       //BYTECODE_POS: 481 
 v-1.objProx = v-1;                //BYTECODE_POS: 482 
 v-1 = executionStack[7];          //BYTECODE_POS: 484 depth
 v0 = executionStack[24];          //BYTECODE_POS: 487 depth
 v-1.sri = v-1;                    //BYTECODE_POS: 490 
 v-1 = executionStack[7];          //BYTECODE_POS: 492 depth
 v0 = executionStack[28];          //BYTECODE_POS: 495 depth
 v1 = executionStack[26];          //BYTECODE_POS: 498 depth
 v0 = v0[v1]                       //BYTECODE_POS: 501 
 v-1.ucwd = v-1;                   //BYTECODE_POS: 502 
 v-1 = executionStack[7];          //BYTECODE_POS: 504 depth
 v0 = undefined                    //BYTECODE_POS: 507 
 v1 = executionStack[27];          //BYTECODE_POS: 508 depth
 v0 = v1();                        //BYTECODE_POS: 511 // context 0 could be custom vm or native func
 v-1.dups = v-1;                   //BYTECODE_POS: 513 
 v-1 = executionStack[7];          //BYTECODE_POS: 515 depth
 v0 = history                      //BYTECODE_POS: 518 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v0.length;                   //BYTECODE_POS: 520 
 v-1.hl = v-1;                     //BYTECODE_POS: 522 
 v-1 = {};                         //BYTECODE_POS: 524 
 executionStack[9] = v-1;          //BYTECODE_POS: 525 // depth = 0
 v-1 = Intl                        //BYTECODE_POS: 528 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v-1                          //BYTECODE_POS: 530 
 v0 = v0.DateTimeFormat;           //BYTECODE_POS: 531 
 v-1 = v0();                       //BYTECODE_POS: 533 // context -1 could be custom vm or native func
 v0 = v-1                          //BYTECODE_POS: 535 
 v0 = v0.resolvedOptions;          //BYTECODE_POS: 536 
 v-1 = v0();                       //BYTECODE_POS: 538 // context -1 could be custom vm or native func
 // if (!v-1) skip to 555          //BYTECODE_POS: 540 
 v-1 = Intl                        //BYTECODE_POS: 542 // return 'new ReferenceError(Z + " is not defined")' if not in globalThis
 v0 = v-1                          //BYTECODE_POS: 544 
 v0 = v0.DateTimeFormat;           //BYTECODE_POS: 545 
 v-1 = v0();                       //BYTECODE_POS: 547 // context -1 could be custom vm or native func
 v0 = v-1                          //BYTECODE_POS: 549 
 v0 = v0.resolvedOptions;          //BYTECODE_POS: 550 
 v-1 = v0();                       //BYTECODE_POS: 552 // context -1 could be custom vm or native func
 // go foward to 556               //BYTECODE_POS: 554 
 v0 = {};                          //BYTECODE_POS: 556 
 executionStack[9] = v0;           //BYTECODE_POS: 557 // depth = 0
 // go foward to 564               //BYTECODE_POS: 560 
 executionStack[11] = v-1;         //BYTECODE_POS: 562 // depth = 0
 v-1 = executionStack[7];          //BYTECODE_POS: 565 depth
 v0 = executionStack[9];           //BYTECODE_POS: 568 depth
 v0 = v0.timeZone;                 //BYTECODE_POS: 571 
 // if (!v0) skip to 581           //BYTECODE_POS: 573 
 v0 = executionStack[9];           //BYTECODE_POS: 575 depth
 v0 = v0.timeZone;                 //BYTECODE_POS: 578 
 // go foward to 583               //BYTECODE_POS: 580 
 v1 = ""                           //BYTECODE_POS: 582 
 v0.tz = v0;                       //BYTECODE_POS: 584 
 v0 = executionStack[7];           //BYTECODE_POS: 586 depth
 v1 = executionStack[9];           //BYTECODE_POS: 589 depth
 v1 = v1.numberingSystem;          //BYTECODE_POS: 592 
 // if (!v1) skip to 602           //BYTECODE_POS: 594 
 v1 = executionStack[9];           //BYTECODE_POS: 596 depth
 v1 = v1.numberingSystem;          //BYTECODE_POS: 599 
 // go foward to 604               //BYTECODE_POS: 601 
 v2 = ""                           //BYTECODE_POS: 603 
 v1.tzS = v1;                      //BYTECODE_POS: 605 
 v1 = executionStack[7];           //BYTECODE_POS: 607 depth
 v2 = executionStack[9];           //BYTECODE_POS: 610 depth
 v2 = v2.calendar;                 //BYTECODE_POS: 613 
 // if (!v2) skip to 623           //BYTECODE_POS: 615 
 v2 = executionStack[9];           //BYTECODE_POS: 617 depth
 v2 = v2.calendar;                 //BYTECODE_POS: 620 
 // go foward to 625               //BYTECODE_POS: 622 
 v3 = ""                           //BYTECODE_POS: 624 
 v2.tzC = v2;                      //BYTECODE_POS: 626 
 v2 = executionStack[7];           //BYTECODE_POS: 628 depth
 v3 = executionStack[9];           //BYTECODE_POS: 631 depth
 v3 = v3.locale;                   //BYTECODE_POS: 634 
 // if (!v3) skip to 644           //BYTECODE_POS: 636 
 v3 = executionStack[9];           //BYTECODE_POS: 638 depth
 v3 = v3.locale;                   //BYTECODE_POS: 641 
 // go foward to 646               //BYTECODE_POS: 643 
 v4 = ""                           //BYTECODE_POS: 645 
 v3.tzL = v3;                      //BYTECODE_POS: 647 
 v3 = executionStack[7];           //BYTECODE_POS: 649 depth
 v4 = executionStack[28];          //BYTECODE_POS: 652 depth
 v5 = executionStack[39];          //BYTECODE_POS: 655 depth
 v4 = v4[v5]                       //BYTECODE_POS: 658 
 v3.perf = v3;                     //BYTECODE_POS: 659 
 v3 = executionStack[7];           //BYTECODE_POS: 661 depth
 v4 = executionStack[28];          //BYTECODE_POS: 664 depth
 v5 = executionStack[40];          //BYTECODE_POS: 667 depth
 v4 = v4[v5]                       //BYTECODE_POS: 670 
 v3.iframeInfo = v3;               //BYTECODE_POS: 671 
 v3 = executionStack[7];           //BYTECODE_POS: 673 depth
 //return v3;                      //BYTECODE_POS: 676 
}