# -*- coding: utf-8 -*-
"""
Created on 2025-01-12 20:47:59
---------
@summary:
---------
@author: poppies
"""

from feapder import Item


class DoubanFeapderItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i douban_feapder
    """

    __table_name__ = "douban_feapder"

    def __init__(self, *args, **kwargs):
        self.detail_text = None
        self.detail_url = None
        # self.id = None
        self.score = None
        self.title = None
